Add a adw-gtk4 package
nickavem/adw-gtk3-copr pull request #1
Opened 2023-02-04 21:18 UTC by PizzaLovingNerd

Hello, I am currently shipping adw-gtk3 in my distro, and recently switched to using your spec instead of my own. So, I am contributing my own spec file for gtk4 support (as well as adding Provides: adw-gtk to get package).

Note that the adw-gtk4-git package will likely only build on Rawhide due to it requiring newer versions of gtk4.

2023-02-08 15:37 UTC, nickavem requested changes
Go ahead and get rid of the -git files. They break way too often, and I should have removed the adw-gtk3 one a lot earlier. Otherwise, I think this will work.

2023-02-18 05:06 UTC, PizzaLovingNerd commented
I deleted the files but it opened a merge conflict

2023-03-26 16:00 UTC, nickavem approved these changes

2023-03-26 16:01 UTC, nickavem commented
I am happy with this. Will integrate into copr package now.

2023-03-26 16:01 UTC, merged